Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,23 +17,19 @@ jobs:
     - name: Install goimports
       run: go install golang.org/x/tools/cmd/goimports@latest
 
-    - name: Get changed files
-      id: files
-      uses: lots0logs/gh-action-get-changed-files@v1.2
-      with:
-        format: 'space-delimited'
+    - name: List all changed files
+      id: get-file
+      run: |
+        echo "FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '.go$')" >> $GITHUB_ENV
 
     - name: Check goimports
       run: |
-        echo "Changed Files: ${{ steps.files.outputs.all }}"
-        for file in ${{ steps.files.outputs.all }}; do
-          if [[ $file == *.go ]]; then
-            goimports -l $file
-            if [ $? -ne 0 ]; then
-              echo "::error file=$file::File does not conform to goimports style"
-              exit 1
-            fi
+        FILES=${FILES}
+        echo "Checking files: $FILES"
+        for FILE in $FILES; do
+          goimports -l $FILE
+          if [ $? -ne 0 ]; then
+            echo "::error file=$FILE::File does not conform to goimports style."
+            exit 1
           fi
         done
-      shell: bash
-
